-- DROP PROCEDURE public.sp_ods_tracelog(timestamp, timestamp);

CREATE OR REPLACE PROCEDURE public.sp_ods_tracelog(IN param_sdate timestamp without time zone, IN param_edate timestamp without time zone)
 LANGUAGE plpgsql
AS $procedure$
	begin
		delete from ods_tracelog
		where time between param_sdate and param_edate
		;
		insert into ods_tracelog(
			time
			,toolid
			,moduleid
			,pg_pressure
			,ig_pressure
			,gas1mfc_flow
			,gas2mfc_flow
			,gas3mfc_flow
			,gas4mfc_flow
			,gas1mfc_flow_set
			,gas2mfc_flow_set
			,gas1mfc_valve_control
			,gas2mfc_valve_control
			,gas3mfc_valve_control
			,gas4mfc_valve_control
			,gas3mfc_flow_set
			,gas4mfc_flow_set
			,dc1power
			,dc1voltage
			,dc1current
			,dc2power
			,dc2voltage
			,dc2current
			,dc3power
			,dc3voltage
			,dc3current
			,rf1vdc
			,rf1pff
			,rf1pr
			,rf1vpp
			,rf1_c1_position
			,rf1_c2_position
			,rf2vdc
			,rf2pf
			,rf2pr
			,rf2vpp
			,rf2_c1_position
			,rf2_c2_position
			,assist_dg_press
			,heater_voltage
			,assist_gas_flow
			,esc_impedance
			,cathode_water_temp
			,stage_water_flow
			,heatertemp
			,wafer1temp
			,wafer2temp
			,heater1current
			,heater2current
			,heater3current
			,escvoltage
			,esccurrent
			,dg1_pressure
			,dg2_pressure
			,chamber_temp1
			,chamber_temp2
			,chamber_temp3
			,chamber_temp4
			,total1life
			,total2life
			,total3life
			,shieldlife
			,shutterlife
			,trap_temp
			,tmp_water_flow
			,cathode_water_flow
			,chamber_water_flow
			,step_process_time
			,process_time
			,pressure
			,esc_impedance_warning_status
			,esc_impedance_error_status
			,magnet_position
			,active_pressure_gauge
			,degas_status
			,active_ion_gauge_filament
			,assist_gas_control_warning_status
			,assist_gas_control_error_status
			,gauge_type
			,drp_pg_pressure
			,apr1_pressure
			,arp2_pressure
			,apr3_pressure
			,apr4_pressure
			,apr5_pressure
			,rpc_pf
			,rpc_pr
			,rpc_resist
			,rpc_vol
			,rpc_freq
			,rpc_ignition
			,ir_arc_detection
			,lifter_position_actual
			,lifter_velocity_actual
			,lifter_acceleration
			,lifter_deceleration
			,heater_temp2
			,corrected_temp_ao
			,uncorrected_temp_ai
			,uuid
		)
		select
			time
			,toolid
			,moduleid
			,pg_pressure
			,ig_pressure
			,gas1mfc_flow
			,gas2mfc_flow
			,gas3mfc_flow
			,gas4mfc_flow
			,gas1mfc_flow_set
			,gas2mfc_flow_set
			,gas1mfc_valve_control
			,gas2mfc_valve_control
			,gas3mfc_valve_control
			,gas4mfc_valve_control
			,gas3mfc_flow_set
			,gas4mfc_flow_set
			,dc1power
			,dc1voltage
			,dc1current
			,dc2power
			,dc2voltage
			,dc2current
			,dc3power
			,dc3voltage
			,dc3current
			,rf1vdc
			,rf1pff
			,rf1pr
			,rf1vpp
			,rf1_c1_position
			,rf1_c2_position
			,rf2vdc
			,rf2pf
			,rf2pr
			,rf2vpp
			,rf2_c1_position
			,rf2_c2_position
			,assist_dg_press
			,heater_voltage
			,assist_gas_flow
			,esc_impedance
			,cathode_water_temp
			,stage_water_flow
			,heatertemp
			,wafer1temp
			,wafer2temp
			,heater1current
			,heater2current
			,heater3current
			,escvoltage
			,esccurrent
			,dg1_pressure
			,dg2_pressure
			,chamber_temp1
			,chamber_temp2
			,chamber_temp3
			,chamber_temp4
			,total1life
			,total2life
			,total3life
			,shieldlife
			,shutterlife
			,trap_temp
			,tmp_water_flow
			,cathode_water_flow
			,chamber_water_flow
			,step_process_time
			,process_time
			,pressure
			,esc_impedance_warning_status
			,esc_impedance_error_status
			,magnet_position
			,active_pressure_gauge
			,degas_status
			,active_ion_gauge_filament
			,assist_gas_control_warning_status
			,assist_gas_control_error_status
			,gauge_type
			,drp_pg_pressure
			,apr1_pressure
			,arp2_pressure
			,apr3_pressure
			,apr4_pressure
			,apr5_pressure
			,rpc_pf
			,rpc_pr
			,rpc_resist
			,rpc_vol
			,rpc_freq
			,rpc_ignition
			,ir_arc_detection
			,lifter_position_actual
			,lifter_velocity_actual
			,lifter_acceleration
			,lifter_deceleration
			,heater_temp2
			,corrected_temp_ao
			,uncorrected_temp_ai
			,gen_random_uuid()
		from tracelog
		where time between param_sdate and param_edate
		;
	
	exception
		when others then 
	        raise exception 'ods_tracelog Error, Code: %', SQLSTATE ;
	END;
$procedure$
;
